import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.00"

[window]
opacity = 0.8

decorations = "None"
#decorations_theme_variant = "Dark"

[font]
normal.family = "Hack"
bold.family = "Hack"
italic.family = "Hack"
bold_italic.family = "Hack"
size = 13.0

